// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.17.0
// source: personSocial.proto

package protogenerated2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SocialFollowers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Youtube int32 `protobuf:"varint,1,opt,name=youtube,proto3" json:"youtube,omitempty"`
	Twitter int32 `protobuf:"varint,2,opt,name=twitter,proto3" json:"twitter,omitempty"`
}

func (x *SocialFollowers) Reset() {
	*x = SocialFollowers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personSocial_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialFollowers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialFollowers) ProtoMessage() {}

func (x *SocialFollowers) ProtoReflect() protoreflect.Message {
	mi := &file_personSocial_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialFollowers.ProtoReflect.Descriptor instead.
func (*SocialFollowers) Descriptor() ([]byte, []int) {
	return file_personSocial_proto_rawDescGZIP(), []int{0}
}

func (x *SocialFollowers) GetYoutube() int32 {
	if x != nil {
		return x.Youtube
	}
	return 0
}

func (x *SocialFollowers) GetTwitter() int32 {
	if x != nil {
		return x.Twitter
	}
	return 0
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age             int32              `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	SocialFollowers []*SocialFollowers `protobuf:"bytes,3,rep,name=socialFollowers,proto3" json:"socialFollowers,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personSocial_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_personSocial_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_personSocial_proto_rawDescGZIP(), []int{1}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetSocialFollowers() []*SocialFollowers {
	if x != nil {
		return x.SocialFollowers
	}
	return nil
}

var File_personSocial_proto protoreflect.FileDescriptor

var file_personSocial_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x77, 0x61, 0x22, 0x45,
	0x0a, 0x0f, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x77,
	0x69, 0x74, 0x74, 0x65, 0x72, 0x22, 0x73, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x77, 0x61, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x52, 0x0f, 0x73, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x32, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_personSocial_proto_rawDescOnce sync.Once
	file_personSocial_proto_rawDescData = file_personSocial_proto_rawDesc
)

func file_personSocial_proto_rawDescGZIP() []byte {
	file_personSocial_proto_rawDescOnce.Do(func() {
		file_personSocial_proto_rawDescData = protoimpl.X.CompressGZIP(file_personSocial_proto_rawDescData)
	})
	return file_personSocial_proto_rawDescData
}

var file_personSocial_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_personSocial_proto_goTypes = []interface{}{
	(*SocialFollowers)(nil), // 0: personwa.SocialFollowers
	(*Person)(nil),          // 1: personwa.Person
}
var file_personSocial_proto_depIdxs = []int32{
	0, // 0: personwa.Person.socialFollowers:type_name -> personwa.SocialFollowers
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_personSocial_proto_init() }
func file_personSocial_proto_init() {
	if File_personSocial_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_personSocial_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialFollowers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personSocial_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_personSocial_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_personSocial_proto_goTypes,
		DependencyIndexes: file_personSocial_proto_depIdxs,
		MessageInfos:      file_personSocial_proto_msgTypes,
	}.Build()
	File_personSocial_proto = out.File
	file_personSocial_proto_rawDesc = nil
	file_personSocial_proto_goTypes = nil
	file_personSocial_proto_depIdxs = nil
}
